### ISSUE TITLE
Auto-build source to image for to push to a registry location

### ISSUE THREAD

**Issue by timothysc** [heptio/eventrouter#1]
We need to setup a turnkey build->test->deploy(dogfood) for this simple service.  

/cc @kensimon

**Comment by timothysc** [comment]
I would like to have src -> image builds once we're ready to tag v0.1.0

**Comment by webwurst** [comment]
I came up with a [`Dockerfile`](https://github.com/giantswarm/docker-eventrouter/blob/master/Dockerfile) for an [`automated build`](https://hub.docker.com/r/giantswarm/eventrouter/) on Docker Hub for the time beeing:
https://github.com/giantswarm/docker-eventrouter/

**Comment by timothysc** [comment]
Autobuilds now post to gcr.io/heptio-images/eventrouter
