### ISSUE TITLE
Prometheus Metrics

### ISSUE THREAD

**Issue by Nalum** [heptio/eventrouter#12]
As well as logging the event I think it would be worth while adding a metrics endpoint for Prometheus.

Do you have plans to do this?

I wouldn't mind contributing to get this off the ground if it was something you'd be happy to take a PR on.

**Comment by timothysc** [comment]
What type of metrics are you looking to add?

**Comment by Nalum** [comment]
Basically convert the kubernetes events into Prometheus metrics.

I think they would need to live along side any Prometheus metrics for the application itself, but right now I am not sure what metrics the app would have or need.

**Comment by timothysc** [comment]
I think some metrics would be worth while to strike the right balance between what is noise and what is signal.  

E.g. - having a error counter I think is absolutely worth having.   

Having counters on successful events is already captured in other signals across the system so it seems like more noise to me, but if you want to patch for it, then go for it.

**Comment by Nalum** [comment]
Yeah, that's more what I'm looking for. I want to be able to alert and chart on any problem events and I want to keep it within prometheus where possible. I'll try getting a start on it.

I guess the first and biggest question is should this be a `sink` or something that is there out of the box?

If it is a `sink` would you want a separate metrics endpoint for `eventrouter` (if there are any metrics to track from it)?

I don't know that it is possible to track multiple metrics endpoints in one pod, I don't think it is.

**Comment by Nalum** [comment]
Are these values okay with you for the prometheus opts?
```
prometheus.CounterOpts{
	Namespace: "heptio",
	Subsystem: "kubernetes",
	Name:      "eventrouter",
}
```
Maybe something more descriptive for the name part?

**Comment by timothysc** [comment]
I think [event-type] makes more sense to me.

**Comment by Nalum** [comment]
Yeah, it made more sense to me looking at them for a little bit :)

I'm also looking at these fields as the label names:

```
"cluster-name":  e.GetObjectMeta().GetClusterName(),
"involved-object-kind": e.InvolvedObject.GetObjectKind().GroupVersionKind().String(),
"involved-object-name": e.InvolvedObject.Name,
"involved-object-namespace": e.InvolvedObject.Namespace,
"reason": e.Reason,
"source": e.Source.Host,
```

**Comment by Nalum** [comment]
Just testing those out and the cluster name does not appear to be set on any of the events in my cluster.

**Comment by timothysc** [comment]
merged.
