### ISSUE TITLE
Deployment without cluster-wide permissions

### ISSUE THREAD

**Issue by ThomasVitt** [heptio/eventrouter#125]
Hi folks,
I'm currently working for a customer who has no cluster-wide access to events, just to a bunch of namespaces. 
This is why the event router is complaining about missing permissions: 
`E0208 20:57:57.020340       1 reflector.go:125] pkg/mod/k8s.io/client-go@v12.0.0+incompatible/tools/cache/reflector.go:98: Failed to list *v1.Event: events is forbidden: User "system:serviceaccount:argocd-test:eventrouter" cannot list resource "events" in API group "" at the cluster scope`
Is it possible to make a change to the tool so it can be deployed to a handful of namespaces? 
Best regads, Thomas

**Comment by aantn** [comment]
@ThomasVitt still relevant?

**Comment by ThomasVitt** [comment]
Yes, it is!

**Comment by ThomasVitt** [comment]
Hey Natan, 
no we refactored the code ourselves in order to view events from multiple namespaces.

**Comment by aantn** [comment]
Got it, cool.
