### ISSUE TITLE
Support for ElasticSearch Forwarding

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/eventrouter#16]
Not unlike #2, but for ElasticSearch for archival and alerting.  In the past when I've worked with a vendor like Datadog, I've asked for [similar visibility](https://github.com/DataDog/dd-agent/issues/2838) into the Events stream.  Now that most of the systems I've got deployed leverage ElasticSearch & X-Pack for logging & alerting, I've lost visibility into the Kubernetes event stream, especially when running in GKE.

**Comment by timothysc** [comment]
So current glog-sink actually pre-supposes that an EFK stack is running.  The logs are formatted for easy indexing in ES.  

https://github.com/heptio/eventrouter/blob/master/sinks/glogsink.go#L27 

Or you want a specific forwarder without the supposition?

**Comment by rosskukulinski** [comment]
oh fabulous! I'm happy with that.  Does the eventrouter lose any events if the Pod its running in is killed?

**Comment by timothysc** [comment]
> Does the eventrouter lose any events if the Pod its running in is killed? 

Currently yes, but I planned on addressing HA ~ 1.7. 

https://github.com/heptio/eventrouter/blob/master/yaml/eventrouter-deployment.yaml#L22

**Comment by rosskukulinski** [comment]
👍 thanks @timothysc. I don't personally have a need for this issue anymore, but I leave it to your discretion whether someone else might :)

**Comment by timothysc** [comment]
Actually I'll leave this open to update docs, so it's clear for other folks.

**Comment by timothysc** [comment]
updated: https://github.com/heptio/eventrouter/commit/4f426f7c28c14237f38b2cbf2e336914456ed2d9 

closing.
