### ISSUE TITLE
Detecting patched deployments

### ISSUE THREAD

**Issue by cemo** [heptio/eventrouter#17]
I am fairly new to k8s land and trying to get our patched deployments. What is the correct way to get deployment updates? I am actually using edit command to patch deployments but could not find an exact fit in prometheus endpoints of eventrouter. I have just seen `heptio_eventrouter_normal{involved_object_kind="ReplicaSet"}` and `heptio_eventrouter_normal{involved_object_kind="Deployment"}` . But these seems to me not exact solution because the number indicates larger values than I expect. What is the correct way to get it?

**Comment by timothysc** [comment]
TBH I'm struggling to understand your question.?.? 

 >  What is the correct way to get deployment updates?  

Is this a general kubernetes question?  If so, it's described here: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/

**Comment by timothysc** [comment]
No word back on issue... closing. 

Feel free to reopen if needed.
