### ISSUE TITLE
Public Image?

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/eventrouter#18]
As an open-source user, I would expect to be able to use the `gcr.io/heptio-images/eventrouter:v0.1` image that is referenced in the `yaml` directory.  At this time, it appears to be a private repo which means I must build, deploy, and manage my own image.

**Comment by timothysc** [comment]
Yes, we wanted to setup our auto-builds.  
I'll enqueue for this week to get the 1st image out there.

**Comment by timothysc** [comment]
k, auto builds should be up.
