### ISSUE TITLE
Why not eventer from the heapster project?

### ISSUE THREAD

**Issue by chancez** [heptio/eventrouter#26]
I'm wondering if you are all aware of the `eventer` tool which does the same things as eventrouter, but is part of the heapster project, https://github.com/kubernetes/heapster/blob/master/events/eventer.go. It's got good support for various sinks, etc. I wonder if perhaps there could be efforts to collaborate instead of rebuilding the same functionality twice. 

I don't work on eventer, but use it heavily, and I'm just curious if there's any reason for not using eventer besides that it's an upstream project and thus development may be slightly slower. If the concern is speed of development, the work could likely be done in a fork, but seems unnecessary to re-do a lot of the work already done in the other project.

**Comment by timothysc** [comment]
Eventrouter was glue to drive further discussion, much of which is currently happening upstream.  

The reason it was done separately, was b/c eventer is tied directly to heapster vs. a separable component.  We knew this from the beginning... and we also used this to drive other initiatives and expose flaws in the current traceability model.  

Right now it sits as a very minimal tool that is useful to anyone running ES and doesn't want to drag in a plethora of dependencies.  Eventually we would like to change several things about events... this tool serves that purpose.
