### ISSUE TITLE
Add JSON output format

### ISSUE THREAD

**Issue by webwurst** [heptio/eventrouter#4]
I would like to store the events in Elasticsearch, `JSON` output would be nice for this.

**Comment by timothysc** [comment]
@webwurst Do you already have EFK stack in place, or do you want a direct push mechanism?

**Comment by webwurst** [comment]
I have already a EFK stack, seeing this `glog` format in Kibana right now. So just `JSON` as output should be enough.

Maybe something based on [`libbeat`](https://github.com/elastic/beats) would also be nice with configurations options for index name or hashed ids to help with deduplication. But not sure and fine for me if added later :smile:

**Comment by timothysc** [comment]
@webwurst done, and thx for the feedback!
